name: Publish zip to release

on:
  release:
    types:
    - published
    branches:
    - main

jobs:
  createZip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
      with:
        ref: main
    - name: Zip old files
      working-directory: './IAVanillaUI/itemsadder-old'
      run: 'zip -r IAVanillaUI-${{ github.event.release.tag_name }}-old.zip data/'
    - name: Zip new files
      working-directory: './IAVanillaUI/itemsadder-new'
      run: 'zip -r IAVanillaUI-${{ github.event.release.tag_name }}-new.zip _iainternal/'
    - name: Upload zip to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'IAVanillaUI/itemsadder-old/IAVanillaUI-${{ github.event.release.tag_name }}-old.zip;IAVanillaUI/itemsadder-new/IAVanillaUI-${{ github.event.release.tag_name }}-new.zip'
        repo-token: '${{ secrets.GITHUB_TOKEN }}'